[theme]
base = "dark"
primaryColor = "#ffffffff"
backgroundColor = "#000000ff"
secondaryBackgroundColor = "#2f2f2fff"
dataframeBorderColor = "#949caa"
borderColor = "#eeff00ff"

[server]
fileWatcherType = "none"