[theme]
base = "dark"
primaryColor = "#FFFF00"
backgroundColor = "#000000ff"
secondaryBackgroundColor = "#2f2f2fff"
dataframeBorderColor = "#949caa"
borderColor = "#FFFFFF"

[server]
fileWatcherType = "none"